#!/bin/bash
set -eu

export GNUPGHOME=~/.gnupg/trezor
gpg2 --list-public-keys --with-keygrip

killall -q trezor-gpg || true
trezor-gpg -v agent &
AGENT_PID=$!
sleep 1

echo "Starting GPG-enabled shell..."
${SHELL}
echo "Stopping GPG-enabled shell..."

kill ${AGENT_PID}
